### ISSUE TITLE
Questions about create_hdf5_edi.py

### ISSUE THREAD

**Issue by ice-cream567** [chensong1995/E-CIR#11]
Hello, I would like to know what the following code does in the load_data function and why it is necessary to subtract 1 from the coordinate value.Thanks.
`if flip:
        x = 239 - x
        y = 179 - y
    else:
        x = x - 1
        y = y - 1`

**Comment by chensong1995** [comment]
Hi ice-cream567,

Thanks for your question! This is to convert the 1-indexed pixel coordinates to 0-indexed pixel coordinates.

I hope this helps! Let me know if you have further concerns.
