### ISSUE TITLE
After running, it shows that the file can't be found, can you provide me a solution, thanks

### ISSUE THREAD

**Issue by xjyp** [chensong1995/E-CIR#8]
![image](https://user-images.githubusercontent.com/28616190/230561385-57b20be6-fd96-4def-b85a-b62ecf158785.png)

**Comment by xjyp** [comment]
![image](https://user-images.githubusercontent.com/28616190/230562150-ab131499-f213-4479-a36f-61859a164209.png)

**Comment by chensong1995** [comment]
Hello xjyp,

Thanks for your interest in our work! Can you please follow the guide [here](https://github.com/chensong1995/E-CIR/blob/main/REDS_Dataset.md) and prepare the REDS dataset? I hope this helps! Let me know if you have other concerns.

**Comment by xjyp** [comment]
Hello chensong1995,

Thank you for your patience in answering. The following data sets you provide should be downloaded all at once, please? My idea before was to add train_{}.hdf5 one by one to run, and when the display is missing, add the required train_{}.hdf5, but I found that I couldn’t read train_1.hdf5. And here I directly download train_{}.hdf5 in OneDrive
![image](https://user-images.githubusercontent.com/28616190/230698168-5ae44cf1-27fa-4279-b971-602ea02bfc2a.png)

**Comment by xjyp** [comment]
Hello chensong1995

Thank you for your patience in answering. The following data sets you provide should be downloaded all at once, please? My idea before was to add train_{}.hdf5 one by one to run, and when the display is missing, add the required .hdf5, but the program finds that it cannot read train_1.hdf5. Here I directly download 16 train_{}.hdf5 in OneDrive, so it should be ok
![image](https://user-images.githubusercontent.com/28616190/230701321-f1b2d4aa-8fa4-4798-95a7-2cb103b54fef.png)

**Comment by chensong1995** [comment]
Thanks for your follow-up!

1. Yes. You need to download all the .hdf5 files before running the code.
2. I am not sure if I understand your question correctly. Are you suggesting you can not read train_1.hdf5 despite all other files being good?
3. Yes. Directly all 16 train_{}.hdf5 files and 2 val_{}.hdf5 files is OK.

I hope this helps! Let me know if you need further assistance.

**Comment by xjyp** [comment]
ok，thank you very much，i will try it again
